version: '3.4'

services:
  loanmanagementapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["flask", "run", "--host", "0.0.0.0", "--port", "5000", "--debugger", "--reload"]
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    restart: unless-stopped
